[build]
command = "npm run build"
publish = "public"

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"
# do not show progress messages when unzipping Cypress
CI = "1"

[[plugins]]
# local Cypress plugin will test our site after it is built
  package = "netlify-plugin-cypress"
  # skip tests against built static site
  [plugins.inputs]
    skip = true
  # but run the tests against the dev version
  [plugins.inputs.preBuild]
    start = 'yarn start'
    wait-on = 'http://localhost:8000/'
    wait-on-timeout = '75' # seconds
  # and run the tests against the deployed preview URL
  [plugins.inputs.onSuccess]
    enable = true
